### PR TITLE
[SUSHI-04] Saving data from big brain app to Mongo

### PR DESCRIPTION
**Pull request by PhantHive**
YouTrack: [PMI-37](https://irisrobotics.youtrack.cloud/issue/PMI-37) [DEV-DATA] NoSQL for Big Brain app
Linked PR: [BB-02](https://github.com/ipsa-scrypt/big-brain/pull/3)

**Context**
In order to improve efficiently the bigbrain AI, we have to get more "real" student data.

This PR involves gathering data from the big brain website post request, and saving it into our mongo cluster.

### CODE REVIEW

**Comment by PhantHive** [comment]
Re-added lint-staged, linter is back again!

**Comment by PyyLog** [comment]
Is it OK for error handling ?

**Comment by PhantHive** [comment]
yes this is a good start

**Comment by PhantHive** [comment]
This PR is ready for review @PyyLog

**Review by PyyLog — APPROVED** [review]
It's all ok for me ! You can go ahead. 💪

**Pull request merged**
